# Generated by Django 5.1.3 on 2025-05-16 04:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_auto_20170108_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='compta.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='provision_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='Provision rate'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='VAT rate'),
        ),
    ]
